parameters:
#    stel_question.example.class: Stel\Bundle\QuestionBundle\Example

services:
#    stel_question.example:
#        class: %stel_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
